### ISSUE TITLE
proposal: kipoigenomics package

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#167]
Currently, many dataloaders are duplicated in Kipoi. It would be great to have a python package `kipoigenomics` which would implement all the common genomics pre-processing functions and dataloaders (like this one https://github.com/kipoi/models/blob/master/DeepSEAKeras/dataloader.py).

Some classes, functions to implement:
- BedToolLinecache
- SeqDataset
  -  automatic interval resizing in case the interval width deviates from the the desired interval
      - `resize(interval, width, fix='center')`

**Comment by lzamparo** [comment]
Great idea

**Comment by Avsecz** [comment]
Will implement this in https://github.com/kipoi/dataloaders

**Comment by Avsecz** [comment]
renamed the package to `kipoiseq` - https://github.com/kipoi/kipoiseq/. All the discussions will be tracked there. closing the issue
