### ISSUE TITLE
Cannot list all the modules

### ISSUE THREAD

**Issue by BoyuanChen** [kipoi/kipoi#211]
Hi,

I am trying to install the package and list the models to get started. I followed the instructions to install the package on ubuntu 16.04. Everything seems works fine. However, when I try to do:
```
import kipoi
kipoi.list_models()
```
I got the error as follows:

Cloning into '/home/$Username/.kipoi/models'...
The authenticity of host 'github.com (xxx.xx.xxx.xxx)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,xxx.xx.xxx.xxx' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Empty DataFrame
Columns: [source]
Index: []

It seems like I am having troubles with downloading the models. Would be possible for you to help with it?

Thanks!

**Comment by Avsecz** [comment]
Seems that github cannot clone public repositories if you don't have ssh keys setup up. I can confirm this bug on a fresh environment (just had it run in a docker container).
### Solution

in `~/.kipoi/config.yaml`, replace:

- `git@github.com:kipoi/models.git` -> `https://github.com/kipoi/models.git`

and run `kipoi ls` again

I'll make this as a default option in Kipoi with the next release

**Comment by Avsecz** [comment]
does that fix your problem?

**Comment by BoyuanChen** [comment]
Yes, that solves the problem. Thanks!
