### ISSUE TITLE
Suggestion: strict rules for allowed dataloader input

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#215]
In order to avoid contributions of dataloaders with arbitrary file formats we should consider restricting inputs (kwargs inputs of dataloaders) to a set of the "common" bioinformatics file formats, which can be extended on request, but only if core Kipoi developers agree. This:

 - Ensures that any bioinformatician can make full use of the models
 - Ensures compatibility between models (easy benchmarking)
 - Makes indel effect prediction (which is not there yet) more feasible

The idea being that a dataloader user can define what analysis should be performed (e.g. which region(s) of the genome should be looked at) **all with the dataloader kwargs bound to bioinformatics formats**. If a dataloader needs extra data that cannot be represented in a standard bioinformatics format then that extra data should either be valid for any input that comes from the dataloader kwargs or raise an error / warning. This "extra data" has to be loaded independently from the dataloader kwargs.

**Comment by Avsecz** [comment]
I'd try to formulate this as a guideline (put to the docs), but not as a strict requirement. It's namely impossible to forsee all the use-cases and file formats. In addition to writing the guidelines in the docs, we can suggest to use a different file format in the PR review.

**Comment by krrome** [comment]
I agree that not all use-cases are foreseeable, but most use-cases would be covered by allowing only the most common bioinformatics formats. I think it would be essential for Kipoi for  e.g. benchmarking / ease of use and for making models accessible to as many people as possible.

Therefore, in my opinion, if file formats are not a strict requirement then I'd at least warn when kipoi test is run and files passed in kwargs are not part of this set. Plus for reviewing we would then need to have an automatic check for that. I think if we don't make that point strong enough we will accumulate dataloader+model combinations that essentially break the idea of a dataloader and with every model that requires a custom input file format we move away from "one-click" predictions for all models. Also, the more we have to point out manually when reviewing models the less efficient we are - but let's see how busy it gets.

**Comment by Avsecz** [comment]
Agree. I would keep it on status quo till zoo starts growing

**Comment by Avsecz** [comment]
This is in-part solved by kipoiseq. This issue should be re-opened in kipoi/models if necessary.
