### ISSUE TITLE
API flag to prohibit model git pull when loading model from kipoi source

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#244]
Problem:
Cluster jobs stall if many jobs try to pull at the same time and create the lock file.

It would be good to have a flag `update: True / False` which defines whether a git pull should be performed on the model repository. This should be accessible through the CLI with an `--ignore-update` or similar flag.

**Comment by Avsecz** [comment]
solved by adding the `auto_update:` flag in https://github.com/kipoi/kipoi/pull/377
