### ISSUE TITLE
Add git to install instructions?

### ISSUE THREAD

**Issue by agitter** [kipoi/kipoi#245]
I have a bio student testing kipoi for a class project.  He got stuck on the git-lfs step of the installation guide because he didn't have git on his Windows machine.  Installing git through conda worked.

I'm not sure whether it is obvious that git needs to be installed before git-lfs.  It was to me, but not for the student.  If it's obvious, please close this.

**Comment by Avsecz** [comment]
Fair point. Added the description to the README and docs.

**Comment by Avsecz** [comment]
Happy to hear about the project:)
