### ISSUE TITLE
automatic "background" variant effect scores for all models

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#251]
To overcome the arbitrariness of variant effect scores in the DeepSEA paper they compare their scores with scores from a set of random variants from the 1000 genomes VCF. In order to replicate that and to get the equivalent of their "e-values", we would have to generate a table of those scores automatically with e.g. the nightly builds.

**Comment by Avsecz** [comment]
This normalization should be part of every model and each model should handle this separately
