### ISSUE TITLE
Add `score_variants` function 

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#256]
The global API of Kipoi should be by default as of the `score_variants` - implemented here: https://github.com/kipoi/models/blob/kipoi_splice/KipoiSplice/4/dataloader.py#L58. predict_snvs is too complicated.

- [x] make this function accessible at: `kipoi.postproc.score_variants`
- [x] add the remaining arguments to the API
  - seq_length
- [x] allow scores to be a mixture of strings and objects as a list or as a dictionary (ala keras api)
- [x] add string->class mapping to https://github.com/kipoi/kipoi/blob/master/kipoi/postprocessing/variant_effects/utils/scoring_fns.py#L12 as present in https://github.com/kipoi/kipoi/blob/master/kipoi/cli/postproc.py#L23
- [x] Use the function in `kipoi.cli.postproc.cli_score_variants`

**Comment by Avsecz** [comment]
Scoring function renaming - https://github.com/kipoi/kipoi/issues/252 - is required by this issue

**Comment by krrome** [comment]
good idea - I'd mainly envision that as a wrapper function around the current `predict_snvs` and moving the relevant function from the `cli.postproc` to `kipoi.postprocessing.variant_effects`

**Comment by Avsecz** [comment]
Exactly. See my first link
