### ISSUE TITLE
Basic runtime error

### ISSUE THREAD

**Issue by GabrielHoffman** [kipoi/kipoi#258]
I set kipoi up on my compute cluster.  Here is my head node info, and the run time error from running kipoi of python 2.7.
 
Is this an issue in my cluster or your end?

`> lsb_release -a`
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.2 (Final)
Release:	6.2
Codename:	Final

# Python 2.7.14
`> kipoi ls`
INFO [kipoi.remote] Update /hpc/users/hoffmg01/.kipoi/models/
error:  while accessing https://github.com/kipoi/models.git/info/refs

fatal: HTTP request failed

**Comment by Avsecz** [comment]
Hm. Do you have internet access on the cluster?

**Comment by GabrielHoffman** [comment]
Yes:
`> ping google.com`
PING google.com (172.217.7.14) 56(84) bytes of data.
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=1 ttl=52 time=1.92 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=2 ttl=52 time=1.91 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=3 ttl=52 time=1.88 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=4 ttl=52 time=1.86 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=5 ttl=52 time=1.84 ms

When I run your command directly:
`>  cd ~/.kipoi/`
`.kipoi> export GIT_LFS_SKIP_SMUDGE=1 && git clone https://github.com/kipoi/models.git`
fatal: destination path 'models' already exists and is not an empty directory.

**Comment by Avsecz** [comment]
can you do:

```bash
cd ~/.kipoi/models
ls
git remote -v
export GIT_LFS_SKIP_SMUDGE=1 && git pull
```

**Comment by Avsecz** [comment]
ok. got the error. Update your git:

![image](https://user-images.githubusercontent.com/10011161/39877002-b4e22bf8-5442-11e8-8c3d-fdabf5750aa4.png)

**Comment by Avsecz** [comment]
you can just install it from conda:

```bash
conda install -c conda-forge git git-lfs
git lfs install
```

**Comment by Avsecz** [comment]
can you do `git --version` before installing it? So that we can keep track of which git versions don't work with github

**Comment by GabrielHoffman** [comment]
Before update: 
`> git --version`
git version 1.7.1

**Comment by Avsecz** [comment]
ok. weird. github said it should work with `>1.6.6`
https://blog.github.com/2011-03-09-git-dumb-http-transport-to-be-turned-off-in-90-days/

**Comment by Avsecz** [comment]
Ok. Great. I'll close the issue
