### ISSUE TITLE
Annotate the vcf file with multiple models

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#262]
It would be nice to be able to annotate the vcf file in one go using multiple models. We could also think about the config file for each model to do the annotation (where we would specify how to post-process the predictions) ala vcfanno (https://github.com/brentp/vcfanno)

```bash
# Without the config file
kipoi postproc model1 model2 model2  \
  --scores=ref alt diff logit_diff
   --input_vcf="in.vcf" \
   -o "in.anno.vcf"

# With config file
kipoi postproc score_variants \
   --config=variant_scoring.config.yaml \
   --input_vcf="in.vcf" \
   -o "in.anno.vcf"
```

**Comment by krrome** [comment]
hmm, I'm in favour of 1) it will just break if the model requirements are incompatible. should have the same then for model prediction.

I don't like 2) with the config file. Seems very convoluted and would increase complexity of the CLI a lot at little benefit. The user should instead use snakemake or whichever pipeline - this keeps things simple and clean also for the user.
