### ISSUE TITLE
Suggestion: Equivalent to `kipoi.get_model` for model description

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#267]
For situations when you just want to load the yaml files, offer an equivalent to `kipoi.get_model`, a la: `kipoi.get_model_descr` that takes the same arguments, has a `default_dataloader`property to generate a dataloader description object etc. I think returning the classes in components.py would be fine as they generally act like the Model and Dataloader classes in terms of metadata / description.
Example use-case: https://github.com/kipoi/kipoi/blob/master/kipoi/postprocessing/gradient_vis/vis.py#L54

**Comment by Avsecz** [comment]
already implemented. Don't know exactly when.

**Comment by krrome** [comment]
https://github.com/kipoi/kipoi/blob/master/kipoi/sources.py#L93
