### ISSUE TITLE
kipoi env install and "-i" flag behave differently

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#273]
The `-i` flag should behave identically to calling `kipoi env install`. Currently for example https://github.com/kipoi/kipoi/blob/master/kipoi/cli/env.py#L77 doesn't get called for `kipoi test -i`. Is there a chance to homogenise this behaviour?

**Comment by krrome** [comment]
also the `-i` flag installs always pytorch-cpu no matter if GPUs are available or not.

**Comment by Avsecz** [comment]
Let's just deprecate -i.

**Comment by krrome** [comment]
should we then automatically check when e.g. `predict` is executed if the requirements are fulfilled and ask the user if they want to install it - or at least give a warning saying how the requirements can be installed?

**Comment by Avsecz** [comment]
That's a great idea. We'd need to go through all the required packages and check if they are available

**Comment by Avsecz** [comment]
And them list the missing ones and spell out the command kipoi env install...

**Comment by Avsecz** [comment]
Or even simpler: we could do try,catch on kipoi.get_model or other commands and watch for a specific exception (package not found) and then print that the user should run kipoi env install or kipoi env create...

**Comment by krrome** [comment]
Additionally on that note `kipoi env create` et al don't allow to automatically install the [vep] packages for kipoi. Once we move Kipoi to conda I would strongly recommend not to have a disambiguation between core Kipoi and kipoi[vep] - if you think that's a bad idea, then I'd rather have all the postprocessing as a separate package.

**Comment by Avsecz** [comment]
Let's have it as a separate package then. Smaller packages are more manageable and It can serve as a bice example of how to build new postprocessing functionality
