### ISSUE TITLE
ParseResult problem when importing (python 3.4.5)

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#297]
Moving conversation of: https://github.com/kipoi/models/issues/98

**Comment by arundurvasula** [comment]
Hi, thanks for the response. I created a new conda environment with python3.6 and reinstalled kipoi with `pip install kipoi` and it seems to be able to import now. I couldn't get this command to work though: `conda install -c bioconda kipoi`

**Comment by Avsecz** [comment]
We actually don't support python 3.4. (We'll make this explicit here https://github.com/kipoi/kipoi/issues/298)

**Comment by Avsecz** [comment]
Please try with python>=3.5 or python=2.7 and open a new issue if it still fails
