### ISSUE TITLE
module 'kipoi' has no attribute 'list_models'

### ISSUE THREAD

**Issue by BoyuanChen** [kipoi/kipoi#307]
Hi,

I am trying to use kipoi to check the available models with python script. I download kipoi in a conda virtual environment with python3.6 and pip. I follow the instructions to install and there is no error on that.

I also did kipoi ls to donwload the models.

However, when I do
```
import kipoi
kipoi.list_models()
```
I got the error: module 'kipoi' has no attribute 'list_models'.

I am running everything on Ubuntu 16.04.

Could you please take a look at it? Thanks in advance!

**Comment by Avsecz** [comment]
Hm. That's very strange. Do `kipoi.get_model` or `kipoi.__version__` exist? If not, then the installation did not work correctly. 

Can you run:
```
pip uninstall kipoi
pip install -U kipoi
```
and print the log output here?

You installed Kipoi using `pip install kipoi`, or?

**Comment by BoyuanChen** [comment]
Oh, I tested it again on a new cluster machine and it works now... I did not really change anything. I am going to close this issue since the issue has been solved. I will still attach what I did just for someone has the same issue:

On Uubuntu 16.04

```
sudo pip3.6 install kipoi
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install -y git git-lfs
git-lfs install
```

Then test it with:
```
python3.6
import kipoi
kipoi.list_models()
```
Things should work. Thanks again!!
