### ISSUE TITLE
concatenation axis of batched writer

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#316]
This might be me using the batch writer wrong, but at the moment the axis of concatenation is the last one, but when iterating over batches the concatenation axis should be the 0th: example:

batch.size is [4,2,1] where 4 means 4 samples of shape [2,1]. this is represented by an array that has  4*2*1 columns and 1 row. But this is not how it should be represented - it should really be [2,1] columns and 4 rows. it becomes evident that varying batch lengths cause problems and also when loading the data, the order of written data is wrong.

**Comment by Avsecz** [comment]
@krrome please provide some examples

**Comment by Avsecz** [comment]
@krrome is this still relevant?
