### ISSUE TITLE
pybedtools dependency

### ISSUE THREAD

**Issue by gokceneraslan** [kipoi/kipoi#321]
Hey,

Is it normal to get ImportError for just `kipoi.get_model("DeepSEA/predict")`? For those who are not interested in variant effect predictions, this should just work with `pip install kipoi` and without the `pip install kipoi[vep]` trick, no?

![image](https://user-images.githubusercontent.com/1140359/43766107-e77441de-9a31-11e8-92b5-1e10ad342d7e.png)

**Comment by gokceneraslan** [comment]
Or a better question would be: what is the ideal way to get any model running by using `get_model()` without going back to the terminal and run kipoi env commands for dependencies?

**Comment by Avsecz** [comment]
Do you need the dataloader or do you want to just use or explore the model itself? If you don't need it, you can run:
```python
model = kipoi.get_model('DeepSEA/predict', with_dataloader=False)
```

If you need it and want to install the required packages from the active python session, you can either run:
```
# Jupyter notebook
!kipoi env install <model>
```

or 
```python
# Python
kipoi.install_model_requirements("<model>")
```

**Comment by gokceneraslan** [comment]
Aah ok, didn't know about ` with_dataloader=False`. But why is it True by default? Shouldn't `get_model` just get the model? 

I mean it's not clear from the quick start document(http://kipoi.org/docs/), or maybe I didn't see it, that users should also install model-specific dependencies, somehow. Maybe an example with `model = kipoi.get_model('DeepSEA/predict', with_dataloader=False)` would help users like me.

**Comment by Avsecz** [comment]
I totally agree with you.

I will add this example to getting started as the short-term solution. However, as the long-term solution I agree that get_model() should only load the model and then the `default_dataloader` should load the dataloader lazily.

**Comment by Avsecz** [comment]
tracking this in https://github.com/kipoi/kipoi/issues/400
