### ISSUE TITLE
`kipoi env cleanup` and `kipoi env remove`

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#372]
- [ ] Keep track of installed kipoi environments at `.kipoi/envs`. set flag after successful installation.
- [ ] If an environment exists with a valid environment name
   - for a model
   - for a pre-compiled environment
 but it is not in `.kipoi/envs` ask the user if this environment has successfully been installed.
- [ ] Before deleting environments ask the user to confirm

**Comment by Avsecz** [comment]
@krrome this was also solved in https://github.com/kipoi/kipoi/pull/379, or?
