### ISSUE TITLE
model environment suggestion

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#373]
Either implement `kipoi env activate <ModelName>` or `kipoi env get <ModelName>`. `kipoi env get <ModelName>` just prints the name of the environment so that `source activate $(kipoi env get <model>)` can be run

alternatively: 
```
kipoie=$(kipoi env get-cli <model>)
kipoie predict ....
```
where `kipoi env get-cli <model>` returns the path path of `kipoi` inside a given environment.

Store the available environments either in a file or in the environment folder itself.

**Comment by Avsecz** [comment]
closed by https://github.com/kipoi/kipoi/pull/379
