### ISSUE TITLE
`get_envs_by_model` don't use absolute model paths

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#389]
Currently, `get_envs_by_model` uses absolute model paths instead of relative:

https://github.com/kipoi/kipoi/blob/master/kipoi/cli/env.py#L295-L307

```python
def get_envs_by_model(models, source, only_most_recent=True, only_valid=False):
    source_path = kipoi.get_source(source).local_path
    entries = []
    db = get_model_env_db()
    for m in models:
        res = db.get_entry_by_model(os.path.join(source_path, m), only_most_recent=only_most_recent,
                                    only_valid=only_valid)
        if only_most_recent:
            entries.append(res)
        else:
            entries.extend(res)
    entries = [e for e in entries if e is not None]
    return entries
```

This causes trouble when using the singularity container as the model paths are not the same between build and run-time. (e.g. at build-time the models are located under `/root/.kipoi/models`).

`get_entry_by_model` should only get the model name and the model source and not the source path.

**Comment by Avsecz** [comment]
Hm. We can ignore source=dir models for now.

**Comment by krrome** [comment]
as in you want to not track those environments in the database?

**Comment by Avsecz** [comment]
Or we can have the following solution: whenever --source=dir is used, we should use the absolute file path and whenever: source=kipoi is used, we should use the actual model name and not the absolute path

**Comment by krrome** [comment]
yeah, I'll do that then..  that's what I meant in my first reply.
