### ISSUE TITLE
Storing numpy object type with HDF5 writer

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#457]
HDF5 writer (https://github.com/kipoi/kipoi/blob/master/kipoi/writers.py#L338) doesn't work with the numpy object tyep[ef `dtype('O')`. To fix this, we would need to use a special type when storing these objects http://docs.h5py.org/en/stable/special.html.

**Comment by DerThorsten** [comment]
Are there any constraints for which types this should work?
 `dtype('O')` is `object` so it could literally be anything. In particular it could even be different for different indices? As far as I understand hdf5 special is just for  variable-length strings, enums or references.

**Comment by Avsecz** [comment]
"Starting with h5py 2.3, variable-length types are not restricted to strings" - seems that we might be able to use also other data types

**Comment by Hoeze** [comment]
Example how it could work:
```python
import numpy as np
import h5py

f = h5py.File('test.h5','w')
dt = h5py.special_dtype(vlen=np.dtype('float64'))
dataset = f.create_dataset('vlen',(4,), dtype=dt)
dataset[()]
```
```python
Out[39]: 
array([array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64)], dtype=object)
```
```python
for i in range(4):
    dataset[i]=np.arange(i+3)

dataset[()]
```
```python
Out[41]:
array([array([0., 1., 2.]), array([0., 1., 2., 3.]),
       array([0., 1., 2., 3., 4.]), array([0., 1., 2., 3., 4., 5.])],
      dtype=object)
```
```python
f.close()
```
