### ISSUE TITLE
bumpversion is deprecated; switch to bump2version?

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#460]
I just saw that setup.py contains `bumpversion` as dependency.
Should we switch to [bump2version](https://github.com/c4urself/bump2version)?
I'ts the more or less official successor of bumpversion.

**Comment by DerThorsten** [comment]
sure feel free to open  a pr

**Comment by Hoeze** [comment]
done in https://github.com/kipoi/kipoi/pull/461 but needs CI fixing.
I also removed enum34 because I think we should deprecate everything < Python 3.4
