### ISSUE TITLE
Have singularity containers for every single model

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#474]
As discussed in our last Kipoi meeting, it would be helpful to continuously build docker / singularity containers for every model. 
This way, it is possible to run them even if old dependencies would be deleted from upstream repositories (conda, PyPI). Also, there would always be a working build of every model available.
Pinning dependencies would therefore be not necessary any more.

Related to https://github.com/kipoi/kipoi/issues/390
Any comments @Avsecz?

**Comment by Avsecz** [comment]
That could be a good idea. It's a major effort to implement this well through and I'm not sure what's the best way to do that.

**Comment by Hoeze** [comment]
I guess it should not be too hard.
Basically, we would need to run the docstrings for every model type in a Dockerfile and have `kipoi predict <model>` as run command in it.
And of course we need to host the containers somewhere (dockerhub?).

The tricky task is to figure out which sub-models fit into the same container.
Nevertheless, this would be a nice first project for a new software dev :grin:

**Comment by haimasree** [comment]
Haha just reading this. I did something similar I suppose? :D
