### ISSUE TITLE
Errors while creating kipoi MMSplice/deltaLogitPSI environment

### ISSUE THREAD

**Issue by glidz** [kipoi/kipoi#493]
Hi, 
I'm a new user, trying to use kipoi for MMSPLICE. I'm working on Ubuntu 20.04, on VMware virtual machine (host is Windows 10). 

I'm trying to create kipoi environment (kipoi env create MMSplice/deltaLogitPSI) both in conda environment and outside, and I get error messages:

in conda environment:
(base) gabil@ubuntu:~$ kipoi env create MMSplice/deltaLogitPSI
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/90c73851
INFO [kipoi.cli.env] Loading model: MMSplice/deltaLogitPSI description
INFO [kipoi.sources] Update /home/gabil/.kipoi/models/
Already up to date.
INFO [kipoi.cli.env] Inferred dataloader name: MMSplice from the model.
INFO [kipoi.cli.env] Environment name: kipoi-MMSplice__deltaLogitPSI
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/90c73851/kipoi-MMSplice__deltaLogitPSI.yaml
INFO [kipoi.cli.env] Done writing the environment file!
Traceback (most recent call last):
  File "/home/gabil/anaconda3/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/home/gabil/anaconda3/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/gabil/anaconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/home/gabil/anaconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 457, in cli_create
    envdb.save()
  File "/home/gabil/anaconda3/lib/python3.7/site-packages/kipoi/env_db.py", line 128, in save
    self.db.purge()
  File "/home/gabil/anaconda3/lib/python3.7/site-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'

outside cinda (user):
gabil@ubuntu:~$ kipoi env create MMSplice/deltaLogitPSI
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/6e94619e
INFO [kipoi.cli.env] Loading model: MMSplice/deltaLogitPSI description
INFO [kipoi.sources] Update /home/gabil/.kipoi/models/
Traceback (most recent call last):
  File "/usr/local/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 443, in cli_create
    env, env_file = export_env(args.model,
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 263, in export_env
    deps = merge_deps(models=models,
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 137, in merge_deps
    sub_models = list_subcomponents(parsed_model, parsed_source, "model")
  File "/usr/local/lib/python3.8/dist-packages/kipoi/sources.py", line 31, in list_subcomponents
    if src._is_component(component, which):
  File "/usr/local/lib/python3.8/dist-packages/kipoi/sources.py", line 745, in _is_component
    self.pull_source()
  File "/usr/local/lib/python3.8/dist-packages/kipoi/sources.py", line 679, in pull_source
    subprocess.call(["git",
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

Any ideas ?
Thank you!

**Comment by MuhammedHasan** [comment]
You should install 'git' with `sudo apt install git`.

**Comment by glidz** [comment]
Hi, this solved the "git" issue, but now I have the "AttributeError: 'Table' object has no attribute 'purge'" error, both in with conda and without:

INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/5ea04275
INFO [kipoi.cli.env] Loading model: MMSplice/deltaLogitPSI description
INFO [kipoi.sources] Update /home/gabil/.kipoi/models/
Already up to date.
INFO [kipoi.cli.env] Inferred dataloader name: MMSplice from the model.
INFO [kipoi.cli.env] Environment name: kipoi-MMSplice__deltaLogitPSI
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/5ea04275/kipoi-MMSplice__deltaLogitPSI.yaml
INFO [kipoi.cli.env] Done writing the environment file!
Traceback (most recent call last):
  File "/usr/local/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/usr/local/lib/python3.8/dist-packages/kipoi/cli/env.py", line 457, in cli_create
    envdb.save()
  File "/usr/local/lib/python3.8/dist-packages/kipoi/env_db.py", line 128, in save
    self.db.purge()
  File "/usr/local/lib/python3.8/dist-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'

**Comment by Avsecz** [comment]
Can you try installing a different tinydb version: `pip install tinydb==4.1.1`?

**Comment by glidz** [comment]
It's the version that I already have:
gabil@ubuntu:~$ sudo pip install tinydb==4.1.1
Requirement already satisfied: tinydb==4.1.1 in /usr/local/lib/python3.8/dist-packages (4.1.1)

**Comment by Avsecz** [comment]
Hm. That's really strange. Your python version doesn't seem to be from conda. Are you using conda? See the installation steps: https://github.com/kipoi/kipoi#installation.

**Comment by glidz** [comment]
I am using conda. tried again to install kipoi (in conda environment), this is the output:

gabil@ubuntu:~$ conda activate
(base) gabil@ubuntu:~$ sudo pip install kipoi
Requirement already satisfied: kipoi in /usr/local/lib/python3.8/dist-packages (0.6.25)
Requirement already satisfied: deprecation>=2.0.6 in /usr/local/lib/python3.8/dist-packages (from kipoi) (2.1.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.8/dist-packages (from kipoi) (4.1.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from kipoi) (2.11.2)
Requirement already satisfied: cookiecutter>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from kipoi) (1.7.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from kipoi) (0.18.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from kipoi) (1.18.4)
Requirement already satisfied: h5py in /usr/local/lib/python3.8/dist-packages (from kipoi) (2.10.0)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3/dist-packages (from kipoi) (1.25.8)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kipoi) (4.46.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.8/dist-packages (from kipoi) (19.3.0)
Requirement already satisfied: kipoi-utils>=0.3.8 in /usr/local/lib/python3.8/dist-packages (from kipoi) (0.3.8)
Requirement already satisfied: kipoi-conda>=0.1.6 in /usr/local/lib/python3.8/dist-packages (from kipoi) (0.2.2)
Requirement already satisfied: pandas>=0.21.0 in /usr/local/lib/python3.8/dist-packages (from kipoi) (1.0.3)
Requirement already satisfied: related>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from kipoi) (0.7.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from kipoi) (5.3.1)
Requirement already satisfied: tinydb in /usr/local/lib/python3.8/dist-packages (from kipoi) (4.1.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from deprecation>=2.0.6->kipoi) (20.4)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2->kipoi) (1.1.0)
Requirement already satisfied: jinja2-time>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (0.2.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (7.1.2)
Requirement already satisfied: binaryornot>=0.4.4 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (0.4.4)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from cookiecutter>=1.6.0->kipoi) (1.14.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (2.23.0)
Requirement already satisfied: python-slugify>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (4.0.0)
Requirement already satisfied: poyo>=0.5.0 in /usr/local/lib/python3.8/dist-packages (from cookiecutter>=1.6.0->kipoi) (0.5.0)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas>=0.21.0->kipoi) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas>=0.21.0->kipoi) (2.7.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->deprecation>=2.0.6->kipoi) (2.4.7)
Requirement already satisfied: arrow in /usr/local/lib/python3.8/dist-packages (from jinja2-time>=0.2.0->cookiecutter>=1.6.0->kipoi) (0.15.6)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3/dist-packages (from binaryornot>=0.4.4->cookiecutter>=1.6.0->kipoi) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.23.0->cookiecutter>=1.6.0->kipoi) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.23.0->cookiecutter>=1.6.0->kipoi) (2019.11.28)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify>=4.0.0->cookiecutter>=1.6.0->kipoi) (1.3)

outside conda the output is very similar. I do get a "warning" that I use pip version 20.1 and I should update to 20.1.1, but that's probably nor the issue...

**Comment by glidz** [comment]
I recently installed the Spliceai tool (https://github.com/Illumina/SpliceAI), also through Conda. 
Could it be that there is a problem with common features?

**Comment by Avsecz** [comment]
No. That's not the problem. Can you paste the output of: `which python`, `which kipoi`, `which pip`, `which conda` commands?

**Comment by Avsecz** [comment]
You shouldn't have to use `sudo` when using conda as the conda will be installed in your home directory typically.

**Comment by Avsecz** [comment]
Maybe using `sudo` is actually the problem. Can you try installing kipoi without `sudo`?

**Comment by glidz** [comment]
Installing kipoi without 'sudo' gives verysimilar output:

(base) gabil@ubuntu:~$ pip install kipoi
Requirement already satisfied: kipoi in ./anaconda3/lib/python3.7/site-packages (0.6.25)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (19.3.0)
Requirement already satisfied: tinydb in ./anaconda3/lib/python3.7/site-packages (from kipoi) (4.1.1)
Requirement already satisfied: colorlog in ./anaconda3/lib/python3.7/site-packages (from kipoi) (4.1.0)
Requirement already satisfied: cookiecutter>=1.6.0 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (1.7.2)
Requirement already satisfied: kipoi-conda>=0.1.6 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (0.2.2)
Requirement already satisfied: deprecation>=2.0.6 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (2.1.0)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from kipoi) (1.18.1)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from kipoi) (0.18.2)
Requirement already satisfied: pandas>=0.21.0 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (1.0.1)
Requirement already satisfied: related>=0.6.0 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (0.7.2)
Requirement already satisfied: h5py in ./anaconda3/lib/python3.7/site-packages (from kipoi) (2.10.0)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.7/site-packages (from kipoi) (4.42.1)
Requirement already satisfied: urllib3>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (1.25.8)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (2.11.1)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.7/site-packages (from kipoi) (5.3)
Requirement already satisfied: kipoi-utils>=0.3.8 in ./anaconda3/lib/python3.7/site-packages (from kipoi) (0.3.8)
Requirement already satisfied: poyo>=0.5.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (0.5.0)
Requirement already satisfied: python-slugify>=4.0.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (4.0.0)
Requirement already satisfied: requests>=2.23.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (2.23.0)
Requirement already satisfied: six>=1.10 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (1.14.0)
Requirement already satisfied: binaryornot>=0.4.4 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (0.4.4)
Requirement already satisfied: MarkupSafe<2.0.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (1.1.1)
Requirement already satisfied: jinja2-time>=0.2.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (0.2.0)
Requirement already satisfied: click>=7.0 in ./anaconda3/lib/python3.7/site-packages (from cookiecutter>=1.6.0->kipoi) (7.0)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.7/site-packages (from deprecation>=2.0.6->kipoi) (20.1)
Requirement already satisfied: python-dateutil>=2.6.1 in ./anaconda3/lib/python3.7/site-packages (from pandas>=0.21.0->kipoi) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas>=0.21.0->kipoi) (2019.3)
Requirement already satisfied: text-unidecode>=1.3 in ./anaconda3/lib/python3.7/site-packages (from python-slugify>=4.0.0->cookiecutter>=1.6.0->kipoi) (1.3)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.23.0->cookiecutter>=1.6.0->kipoi) (2019.11.28)
Requirement already satisfied: chardet<4,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.23.0->cookiecutter>=1.6.0->kipoi) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.23.0->cookiecutter>=1.6.0->kipoi) (2.8)
Requirement already satisfied: arrow in ./anaconda3/lib/python3.7/site-packages (from jinja2-time>=0.2.0->cookiecutter>=1.6.0->kipoi) (0.15.6)
Requirement already satisfied: pyparsing>=2.0.2 in ./anaconda3/lib/python3.7/site-packages (from packaging->deprecation>=2.0.6->kipoi) (2.4.6)

**Comment by Avsecz** [comment]
Ok great. This now actually installed kipoi into your conda (see the `anaconda3` path in the output`. Can you type `which kipoi` now?

**Comment by glidz** [comment]
These are the 'which' outputs: 

Inside conda:

(base) gabil@ubuntu:~$ which python
/home/gabil/anaconda3/bin/python
(base) gabil@ubuntu:~$ which kipoi
/home/gabil/anaconda3/bin/kipoi    ## this was like that before the last installment
(base) gabil@ubuntu:~$ which pip
/home/gabil/anaconda3/bin/pip
(base) gabil@ubuntu:~$ which conda
/home/gabil/anaconda3/bin/conda
(base) gabil@ubuntu:~$ 

outside conda (Yes, I've installed kipoi several times)
gabil@ubuntu:~$ which python
gabil@ubuntu:~$ python

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

gabil@ubuntu:~$ which python3
/usr/bin/python3
gabil@ubuntu:~$ which kipoi
/usr/local/bin/kipoi
gabil@ubuntu:~$ which pip
/usr/local/bin/pip
gabil@ubuntu:~$ which conda
/home/gabil/anaconda3/condabin/conda
gabil@ubuntu:~$ 


Maybe the issue is al the 'kipoi' locations? (and python names?)
Maybe I should remove kipoi from all locations and start again

**Comment by Avsecz** [comment]
Ok. you have to have conda activated when running `kipoi` commands (as you did at the beginning). After activating conda, can you also run `pip install tinydb==4.1.1`?

**Comment by glidz** [comment]
gabil@ubuntu:~$ conda activate
(base) gabil@ubuntu:~$ pip install tinydb==4.1.1
Requirement already satisfied: tinydb==4.1.1 in ./anaconda3/lib/python3.7/site-packages (4.1.1)
(base) gabil@ubuntu:~$

**Comment by Avsecz** [comment]
Ok. One workaround this problem would be to manually install the environment:

```bash
kipoi env export -e mmsplice -o mmsplice-conda.yaml
conda env create -f mmsplice-conda.yaml
conda activate mmsplice
```

**Comment by glidz** [comment]
That's interesting, I got the 'usage' message:

(base) gabil@ubuntu:~$ kipoi env export -e mmsplice -o mmsplice-conda.yaml
usage: kipoi env export [-h] [--source {kipoi,github-permalink,dir}]
                        [--dataloader DATALOADER [DATALOADER ...]] [--vep]
                        [--interpret] [--gpu] -o OUTPUT [-e ENV]
                        model [model ...]
kipoi env export: error: the following arguments are required: model
(base) gabil@ubuntu:~$ conda env create -f mmsplice-conda.yaml

EnvironmentFileNotFound: '/home/gabil/mmsplice-conda.yaml' file not found

**Comment by Avsecz** [comment]
Oh. I forgot to add the model name: 

```
kipoi env export -e mmsplice -o mmsplice-conda.yaml MMSplice/deltaLogitPSI
```

**Comment by glidz** [comment]
That worked! 
Took several minutes, but the mmsplice environment was created and activated. Now I just need to learn how to work with the mmsplice...

Thank you very much!
