### ISSUE TITLE
Building documentation fails because new pydoc-markdown v3 is a full rewrite

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#499]
We cannot use the old pydoc-markdown as well because it depends on python2 and I cannot get it to work.

We have to update or switch to something else.
Any thoughts @Avsecz ?
AFAIK sphinx is the most widely used documentation generator today.

**Comment by Avsecz** [comment]
Is there a newer version of pydoc markdown?

**Comment by Hoeze** [comment]
wow i missed your question somehow @Avsecz, sorry for that.
Yes, here:
https://github.com/NiklasRosenstein/pydoc-markdown
However, no clue what has to be done to upgrade.

**Comment by Avsecz** [comment]
pydoc-markdown also works with python3. I've updated the CI config to always take our pydoc-markdown version frozen in time https://github.com/kipoi/kipoi/commit/9fa943a4745ac8328e6c75d8ebe38506eca5c562
