### ISSUE TITLE
module 'torch.jit' has no attribute 'get_trace_graph'

### ISSUE THREAD

**Issue by Shunili** [kipoi/kipoi#554]
In the Concise package, both GradientXInput and Gradient functions are not working. 

```
grxinp = GradientXInput(deep_sea)
val = grxinp.score(seqa)[0]

gr = Gradient(deep_sea)
val = gr.score(seqa)
```

Both would give the following error:
AttributeError: module 'torch.jit' has no attribute 'get_trace_graph'

I think after torch 1.1, `get_trace_graph` is replace by  `torch.jit._get_trace_graph`.

https://github.com/kipoi/kipoi/blob/7614b532db88253f2f3b11cf3a5691052ce2150a/kipoi/model.py#L1078

**Comment by haimasree** [comment]
@Shunili 
Did you encounter this problem while trying a specific model inside kipoi?

**Comment by Shunili** [comment]
I was trying the DeepSEA/predict model.

**Comment by haimasree** [comment]
Which conda environment are you using? kipoi-DeepSEA__predict?

Can you try the following and report back please?
 
```
conda create --name py36 python=3.6
conda activate py36
pip install kipoi
kipoi env create shared/envs/kipoi-py3-keras2 --verbose (Make sure the environment is created correctly. If verbose flag is not specified, this command can fail silently. This has been fixed at the source https://github.com/kipoi/kipoi-utils/pull/25 but kipoi package is not up to date I think)
conda activate kipoi-shared__envs__kipoi-py3-keras2
```
and try to run your script here.

**Comment by haimasree** [comment]
Also: I pushed a change here - https://github.com/kipoi/models/blob/fix_deepsea_predict/DeepSEA/predict/model.yaml
Can you checkout this branch and see if it is helping?

**Comment by Shunili** [comment]
Thank you for the quick response.
I was using the shared/envs/kipoi-py3-keras2 env before, but I cannot remember if I had the verbose flag when I first created it. I re-created the environment with --verbose flag and it solved the problem.

**Comment by haimasree** [comment]
Great! It worked without changing the pytorch version you mean?

**Comment by Shunili** [comment]
Yeah, that's right. I'm not sure why that's the case, maybe the new env picks up the correct torch version?

**Comment by haimasree** [comment]
Thats great then :D. I am closing the issue :)
