### ISSUE TITLE
kipoi_veff scoring_function support for DeepSEA/Beluga

### ISSUE THREAD

**Issue by TzuTingWei** [kipoi/kipoi#579]
I used the kipoi_veff scoring_function on DeepSEA/variant effect model before, but I also want to use DeepSEA/Beluga model which currently doesn’t have a scoring function. Is it possible to add this function so that I could use kipoi_veff to extract the prediction? Thank you!

**Comment by Avsecz** [comment]
Made a PR with that feature: https://github.com/kipoi/models/pull/235
