### ISSUE TITLE
Alternative dataloader not working as intended

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#582]
```bash
kipoi predict Framepool --dataloader_args='{"feature_type":"5UTR","gtf_file":"/s/genomes/human/hg19/gencode29/gencode.v29lift37.annotation.gtf.gz","fasta_file":"/s/genomes/human/hg19/fasta/hg19.fa","vcf_file":"vcf.vcf.gz"}' -o test_kipoiseq.tsv --dataloader kipoiseq.dataloaders.SingleVariantUTRDataLoader                           
```
```python
INFO [kipoi.sources] Update [...]/.kipoi/models/
Already up to date.
INFO [kipoi.data] successfully loaded the dataloader Framepool/. from [...]/.kipoi/models/Framepool/dataloader.py::StrandedSequenceVariantDataloader
INFO [kipoi.model] Downloading model arguments weights from https://zenodo.org/record/3584238/files/Framepool_combined_residual.h5?download=1
Using downloaded and verified file: [...]/.kipoi/models/Framepool/downloaded/model_files/weights/d1e9656725e730d509a09d5371e51bd2
INFO [kipoi.pipeline] dataloader.output_schema is compatible with model.schema
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/cli/main.py", line 242, in cli_predict
    Dl = kipoi.get_dataloader_factory(args.dataloader, args.dataloader_source)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/data.py", line 629, in get_dataloader
    source.pull_dataloader(dataloader)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/sources.py", line 341, in pull_dataloader
    self._pull_component(dataloader, "dataloader")
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/sources.py", line 723, in _pull_component
    component_dir = self.local_source._get_component_dir(component, which)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/sources.py", line 544, in _get_component_dir
    self.assert_is_component(component, which)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/sources.py", line 334, in assert_is_component
    raise ValueError("{} {} doesn't exist".format(which, component))
ValueError: dataloader kipoiseq.dataloaders.SingleVariantUTRDataLoader doesn't exist
```

Why does Kipoi not find the correct dataloader here?
I'm using latest Kipoi + kipoiseq.

Workaround is this pull request:
https://github.com/kipoi/models/pull/234

**Comment by haimasree** [comment]
Current version (0.5.2) of kipoiseq package  does not contain SingleVariantUTRDataLoader. I think the above error is related to this. Can you publish a new package please? We can verify this theory afterwards.

**Comment by Hoeze** [comment]
Hi @haimasree, I just checked and as far as I can see, it is already contained:
https://files.pythonhosted.org/packages/c7/9f/ccecef386026bf7f86bad097ae7f59c0dbcb7aa83c5705761ab2fda36c3b/kipoiseq-0.5.2.tar.gz
Also, when I run the import, it works:
```python
# conda activate /opt/modules/i12g/anaconda/envs/kipoi-Framepool2/
# ipython
In [1]: import kipoiseq
In [2]: kipoiseq.dataloaders.SingleVariantUTRDataLoader
Out[2]: kipoiseq.dataloaders.protein.SingleVariantUTRDataLoader
```

**Comment by haimasree** [comment]
Okay thank you for tying out. We have a real bug here. I will unassign you and I see if I can find the bug.

**Comment by haimasree** [comment]
Alright I did a bit of digging. This is rather complicated so I will keep it brief. [Here](https://github.com/kipoi/kipoi/blob/master/kipoi/data.py#L629) is the problematic part.

By default, source is kipoi. This forces the code to only look for data loader definition in the checked out model repository. This explains why updating Framepool  model repo directly had the intended effect.

The two other options for source is "github-permalink" and "dir". However, I dont think you can just update the dataloader separately even if source is dir - atleast I did not see any code which could address this. The definition of dataloader is tied to the respective model.yaml as far as I can see. 

@Avsecz Can you verify this please?

**Comment by Avsecz** [comment]
I think the issue is that we assume in the codebase that a dataloader will be implemented as a dataloader.yaml file rather than a python module. So this is basically a new feature request.

There seems to have been an attempt to load the dataloader from python source: https://github.com/kipoi/kipoi/blob/master/kipoi/data.py#L620 (commented-out). (PR: https://github.com/kipoi/kipoi/commit/1c00c77b1e64d89c4bbd65aca72be1dcb2cea83e). I think we'd need to add something like that:
```
if source == 'py':
  CustomDataLoader = load_obj(dataloader)
else:
    if isinstance(source, str):
        source = kipoi.config.get_source(source)
    source.pull_dataloader(dataloader)
    dataloader_dir = source.get_dataloader_dir(dataloader)
    ...
```

@Hoeze In that case, you'd still need to specify `--dataloader_source=py` which may be a bit tricky to remember. An alternative would be to try to load the dataloader directly and fallback to the usual `kipoi` source if an exception will be raised. Any thoughts on what you would expect to happen?

**Comment by Hoeze** [comment]
+1 for your suggestion @Avsecz. 
We just have to make sure not to secretly choose another dataloader, as this could cause confusion.

If I got it right, there will be basically three ways to specify the dataloader then:
- by module path:
e.g. `kipoi.models.Framepool.VariantEffect.SingleVariantUTRDataloader`
- by directory path, either relative to the kipoi/models dir (`--source=kipoi`) or the current working dir (`--source=dir`):
e.g. `Framepool/VariantEffect/dataloader.py::SingleVariantUTRDataloader`

We could add some default option `--source=infer`, that works in the following manner:
1) Try to `import` the path
2) If failed, try to load file path from `kipoi/models`
3) If failed, try to load relative to current working directory

In each case, a warning should be printed:
`WARNING: loading dataloader from [...]. Set "--source=[...]" to ensure consistent usage of this dataloader.`

Now the only question is: How would one ensure that for the default dataloader `--source=kipoi` is selected?

-----

Another idea would be to support format strings and/or URI's like this:
- `file://{kipoi_model_dir}/Framepool/VariantEffect/dataloader.py::SingleVariantUTRDataloader`
- `file://{kipoi_model_dir}/Framepool/VariantEffect/dataloader.yaml`

However, at some point the supported options get overwhelming.
