### ISSUE TITLE
Model kipoi-py3-keras2 not found in source kipoi

### ISSUE THREAD

**Issue by jiangshan529** [kipoi/kipoi#592]
Hi, I followed the tutorial to create kipoi environment like this :
in the ./kipoi folder(which contains config.yaml), I print: kipoi env create kipoi-py3-keras2,
it reports the error: Model kipoi-py3-keras2 not found in source kipoi.

**Comment by haimasree** [comment]
Can you please let me know which link you got the above instruction from? Please try the following
```
kipoi env create shared/envs/kipoi-py3-keras2 
```

**Comment by jiangshan529** [comment]
> Can you please let me know which link you got the above instruction from? Please try the following
> 
> ```
> kipoi env create shared/envs/kipoi-py3-keras2 
> ```

I use this link: http://kipoi.org/docs/index.html#links.
If I use the code you showed, it reports:
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/d5ace88b
INFO [kipoi.cli.env] Loading environment definition: shared/envs/kipoi-py3-keras2
INFO [kipoi.cli.env] Environment name: kipoi-shared__envs__kipoi-py3-keras2
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/d5ace88b/kipoi-shared__envs__kipoi-py3-keras2.yaml
WARNING [kipoi.specs] Swapping channel order - putting defaults last. Using pysam bioconda instead of anaconda
WARNING [kipoi.specs] Swapping channel order - putting defaults last. Using pysam bioconda instead of anaconda
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.sources] Update /home/baijsh/.kipoi/models/
Already up-to-date.
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/d5ace88b/kipoi-shared__envs__kipoi-py3-keras2.yaml.
It stayed at the last sentence for 10 min and no change and no end.

**Comment by jiangshan529** [comment]
> Can you please let me know which link you got the above instruction from? Please try the following
> 
> ```
> kipoi env create shared/envs/kipoi-py3-keras2 
> ```

Yes, now it works, and I can source activate kipoi-shared__envs__kipoi-py3-keras2. and then I write a python script:
```
import kipoi
kipoi.list_models()
```
When I run it, it shows: AttributeError: module 'kipoi' has no attribute 'list_models'

**Comment by haimasree** [comment]
Hi, did you activate the environment  called kipoi-py3-keras2 with either source activate or conda activate?
Maybe paste the output of 
```
conda env list
```
You need to execute this script in the environment you just created.

**Comment by haimasree** [comment]
Hi, did your issue get resolved?

**Comment by haimasree** [comment]
I am closing this issue as I did not hear back form you. Feel free to re-open if you need further help.
