### ISSUE TITLE
Some broken links in documentation

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#597]
Found by @Tdsone:

- http://kipoi.org/docs/tutorials/contributing_models.html:
  - http://kipoi.org/docs/contributing/01_Getting_started/ -> http://kipoi.org/docs/contributing/01_Getting_started.html
- http://kipoi.org/docs/using/python.html
  - http://kipoi.org/tutorials/python-api/ -> http://kipoi.org/docs/tutorials/python-api.html

**Comment by haimasree** [comment]
Fixed by: #598, #599 and 05977083f3941d2541c086a7114f71acbcba5de2
