### ISSUE TITLE
Drop Python3.6 support

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoi#643]
A lot of libraries already dropped python 3.6 support.
Most prominently, NumPy v1.22 requires already `python>=3.8`.
Should we also consider updating our minimum supported python versions to at least `python>=3.7`?

(I'd also have no issue with `python>=3.8` if there are no complains)

**Comment by haimasree** [comment]
As far as I know there are quite a few users who use python 3.6. So dropping it altogether may not be ideal.
Also: Are any of these libraries used by core part of  kipoi? 
 If you have trouble running a specific test with python 3.6 you could use the trick I used when I was adding support and tests for Tensorflow2 which is only supported by python>3.8. Tests [here](https://github.com/kipoi/kipoi/tree/master/tests/legacy) only get tested with python 3.6 and 3.7. [CI](https://github.com/kipoi/kipoi/blob/master/.circleci/config.yml) ignores this folder if python=3.8/3.9 and tests all of them if python=3.6/3.7.

@Avsecz Any thoughts?

**Comment by Hoeze** [comment]
@haimasree Do you know if these models would just break with py3.8?
Or is it an issue with old non-maintained dependencies?

**Comment by haimasree** [comment]
For example - [this test](https://github.com/kipoi/kipoi/blob/master/tests/legacy/test_KerasModel.py) wont pass with python>=3.8.
