### ISSUE TITLE
Variant effect prediction also for indels

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#66]
Enhance variant effect prediction to work with indels too.

**Comment by krrome** [comment]
one idea to solve correct dataloader input generation is by rewriting the input fasta (this is required in for the proposed algorithm), defining a different "seqname" / "chromosome-like" sequence for every allele of a variant - the coordinates of all the other dataloader input files (bed, GTF files etc.) would then have to be subset / lifted over accordingly.
This mainly requires extensive flagging in the dataloader.yaml:

A definition of groups of files that should be lifted over consistently the following way:
- A `group-name` flag for a `.fasta` file
- every dataloader input file that should be subject to this lifting-over should then also be tagged with this `group-name`.
- non-standatd input file formats will not be processable

How to handle multiple (>1) such groups is unclear / not definable.

**Comment by Avsecz** [comment]
in-del computation should be part of kipoiseq
